// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: policyCheckpointGateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PolicyCheckpointGateway_RequestStateWrite_FullMethodName    = "/dynamos.PolicyCheckpointGateway/RequestStateWrite"
	PolicyCheckpointGateway_ValidateStateRead_FullMethodName    = "/dynamos.PolicyCheckpointGateway/ValidateStateRead"
	PolicyCheckpointGateway_SubscribeStateEvents_FullMethodName = "/dynamos.PolicyCheckpointGateway/SubscribeStateEvents"
	PolicyCheckpointGateway_Shutdown_FullMethodName             = "/dynamos.PolicyCheckpointGateway/Shutdown"
)

// PolicyCheckpointGatewayClient is the client API for PolicyCheckpointGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyCheckpointGatewayClient interface {
	// Before every state write. Gateway consults the active agreement,
	// decides, persists on ALLOW, and appends to audit before returning.
	// On DENY no payload is persisted; the denial is audited.
	RequestStateWrite(ctx context.Context, in *StateWriteRequest, opts ...grpc.CallOption) (*StateDecision, error)
	// When the MS wants to reuse prior state — on restart or mid-run.
	ValidateStateRead(ctx context.Context, in *StateReadRequest, opts ...grpc.CallOption) (*StateReadResponse, error)
	// Long-lived server stream. MS subscribes at startup; gateway pushes
	// PURGE / FREEZE / AGREEMENT_CHANGED. Replaces any reverse-RPC.
	SubscribeStateEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PolicyCheckpointGateway_SubscribeStateEventsClient, error)
	// Lets the dependent stateful MS terminate the gateway during its
	// SafeExit, so the Job pod can reach Succeeded. Identity-verified.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type policyCheckpointGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyCheckpointGatewayClient(cc grpc.ClientConnInterface) PolicyCheckpointGatewayClient {
	return &policyCheckpointGatewayClient{cc}
}

func (c *policyCheckpointGatewayClient) RequestStateWrite(ctx context.Context, in *StateWriteRequest, opts ...grpc.CallOption) (*StateDecision, error) {
	out := new(StateDecision)
	err := c.cc.Invoke(ctx, PolicyCheckpointGateway_RequestStateWrite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyCheckpointGatewayClient) ValidateStateRead(ctx context.Context, in *StateReadRequest, opts ...grpc.CallOption) (*StateReadResponse, error) {
	out := new(StateReadResponse)
	err := c.cc.Invoke(ctx, PolicyCheckpointGateway_ValidateStateRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyCheckpointGatewayClient) SubscribeStateEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PolicyCheckpointGateway_SubscribeStateEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PolicyCheckpointGateway_ServiceDesc.Streams[0], PolicyCheckpointGateway_SubscribeStateEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &policyCheckpointGatewaySubscribeStateEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PolicyCheckpointGateway_SubscribeStateEventsClient interface {
	Recv() (*StateEvent, error)
	grpc.ClientStream
}

type policyCheckpointGatewaySubscribeStateEventsClient struct {
	grpc.ClientStream
}

func (x *policyCheckpointGatewaySubscribeStateEventsClient) Recv() (*StateEvent, error) {
	m := new(StateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *policyCheckpointGatewayClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PolicyCheckpointGateway_Shutdown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyCheckpointGatewayServer is the server API for PolicyCheckpointGateway service.
// All implementations must embed UnimplementedPolicyCheckpointGatewayServer
// for forward compatibility
type PolicyCheckpointGatewayServer interface {
	// Before every state write. Gateway consults the active agreement,
	// decides, persists on ALLOW, and appends to audit before returning.
	// On DENY no payload is persisted; the denial is audited.
	RequestStateWrite(context.Context, *StateWriteRequest) (*StateDecision, error)
	// When the MS wants to reuse prior state — on restart or mid-run.
	ValidateStateRead(context.Context, *StateReadRequest) (*StateReadResponse, error)
	// Long-lived server stream. MS subscribes at startup; gateway pushes
	// PURGE / FREEZE / AGREEMENT_CHANGED. Replaces any reverse-RPC.
	SubscribeStateEvents(*SubscribeRequest, PolicyCheckpointGateway_SubscribeStateEventsServer) error
	// Lets the dependent stateful MS terminate the gateway during its
	// SafeExit, so the Job pod can reach Succeeded. Identity-verified.
	Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPolicyCheckpointGatewayServer()
}

// UnimplementedPolicyCheckpointGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyCheckpointGatewayServer struct {
}

func (UnimplementedPolicyCheckpointGatewayServer) RequestStateWrite(context.Context, *StateWriteRequest) (*StateDecision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestStateWrite not implemented")
}
func (UnimplementedPolicyCheckpointGatewayServer) ValidateStateRead(context.Context, *StateReadRequest) (*StateReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateStateRead not implemented")
}
func (UnimplementedPolicyCheckpointGatewayServer) SubscribeStateEvents(*SubscribeRequest, PolicyCheckpointGateway_SubscribeStateEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeStateEvents not implemented")
}
func (UnimplementedPolicyCheckpointGatewayServer) Shutdown(context.Context, *ShutdownRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPolicyCheckpointGatewayServer) mustEmbedUnimplementedPolicyCheckpointGatewayServer() {
}

// UnsafePolicyCheckpointGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyCheckpointGatewayServer will
// result in compilation errors.
type UnsafePolicyCheckpointGatewayServer interface {
	mustEmbedUnimplementedPolicyCheckpointGatewayServer()
}

func RegisterPolicyCheckpointGatewayServer(s grpc.ServiceRegistrar, srv PolicyCheckpointGatewayServer) {
	s.RegisterService(&PolicyCheckpointGateway_ServiceDesc, srv)
}

func _PolicyCheckpointGateway_RequestStateWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyCheckpointGatewayServer).RequestStateWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyCheckpointGateway_RequestStateWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyCheckpointGatewayServer).RequestStateWrite(ctx, req.(*StateWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyCheckpointGateway_ValidateStateRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyCheckpointGatewayServer).ValidateStateRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyCheckpointGateway_ValidateStateRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyCheckpointGatewayServer).ValidateStateRead(ctx, req.(*StateReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyCheckpointGateway_SubscribeStateEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyCheckpointGatewayServer).SubscribeStateEvents(m, &policyCheckpointGatewaySubscribeStateEventsServer{stream})
}

type PolicyCheckpointGateway_SubscribeStateEventsServer interface {
	Send(*StateEvent) error
	grpc.ServerStream
}

type policyCheckpointGatewaySubscribeStateEventsServer struct {
	grpc.ServerStream
}

func (x *policyCheckpointGatewaySubscribeStateEventsServer) Send(m *StateEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PolicyCheckpointGateway_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyCheckpointGatewayServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyCheckpointGateway_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyCheckpointGatewayServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyCheckpointGateway_ServiceDesc is the grpc.ServiceDesc for PolicyCheckpointGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyCheckpointGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamos.PolicyCheckpointGateway",
	HandlerType: (*PolicyCheckpointGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestStateWrite",
			Handler:    _PolicyCheckpointGateway_RequestStateWrite_Handler,
		},
		{
			MethodName: "ValidateStateRead",
			Handler:    _PolicyCheckpointGateway_ValidateStateRead_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PolicyCheckpointGateway_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeStateEvents",
			Handler:       _PolicyCheckpointGateway_SubscribeStateEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policyCheckpointGateway.proto",
}
